Document: tlp-config
Title: Debian tlp-config Manual
Author: <insert document author here>
Abstract: This manual describes what tlp-config is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tlp-config/tlp-config.sgml.gz

Format: postscript
Files: /usr/share/doc/tlp-config/tlp-config.ps.gz

Format: text
Files: /usr/share/doc/tlp-config/tlp-config.text.gz

Format: HTML
Index: /usr/share/doc/tlp-config/html/index.html
Files: /usr/share/doc/tlp-config/html/*.html
